apiVersion: v1
kind: Service
metadata:
  name: classtimetable-writer
  labels:
    run: classtimetable-writer
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: classtimetable-writer
  type: LoadBalancer
