apiVersion: batch/v1
kind: Job
metadata:
  name: esandospopulator
spec:
  template:
    metadata:
      name: esandospopulator
      labels:
        app: esandospopulator
        tier: backend
        bump: bump-7
    spec:
      volumes:
        - name: "mongodb-cacerts"
          secret:
            secretName: "mongodbkeystore"
      containers:
        - name: esandospopulator
          image: eu.gcr.io/time-to-teach-zone/esandospopulator:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGODB_HOST
              value: "10.0.2.2"
            - name: MONGODB_PORT
              value: "27017"
            - name: MINIKUBE_RUN
              value: "true"
            - name: MONGODB_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: mongoconnectionuri
                  key: mongoconnectionuri
                  optional: true
            - name: MONGODB_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodbkeystorepassword
                  key: mongodbkeystorepassword
                  optional: true
          volumeMounts:
            - name: "mongodb-cacerts"
              mountPath: "/etc/ssl/"
          resources:
            limits:
              cpu: 300m
              memory: 1024Mi
            requests:
              cpu: 200m
              memory: 512Mi
      restartPolicy: Never
