apiVersion: batch/v1
kind: Job
metadata:
  name: test-populator
spec:
  template:
    metadata:
      name: test-populator
    spec:
      volumes:
        - name: "mongodb-cacerts"
          secret:
            secretName: "mongodbkeystore"
      containers:
      - name: esandospopulator
        image: eu.gcr.io/time-to-teach-zone/test-populator:latest
        imagePullPolicy: Always
        env:
          - name: MONGODB_HOST
            value: "10.0.2.2"
          - name: MONGODB_PORT
            value: "27017"
          - name: MONGODB_CONNECTION_URI
            valueFrom:
              secretKeyRef:
                name: mongoconnectionuri
                key: mongoconnectionuri
                optional: true
          - name: MONGODB_KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodbkeystorepassword
                key: mongodbkeystorepassword
                optional: true
        volumeMounts:
          - name: "mongodb-cacerts"
            mountPath: "/etc/ssl/"
        resources:
          limits:
            cpu: 300m
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 512Mi
      restartPolicy: Never
