apiVersion: v1
kind: Service
metadata:
  name: user-reader
  labels:
    run: user-reader
spec:
  ports:
    - port: 7002
      targetPort: 443
      protocol: TCP
  selector:
    app: user-reader
  type: LoadBalancer
