apiVersion: v1
kind: Service
metadata:
  name: timetoteach-ui-service
  labels:
    run: timetoteach-ui-service
spec:
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: timetoteach-ui-server
  type: LoadBalancer
