apiVersion: v1
kind: Service
metadata:
  name: scriptwriter-service
  labels:
    run: scriptwriter-service
spec:
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: scriptwriter
  clusterIP: 10.7.255.236
  type: LoadBalancer
