apiVersion: v1
kind: Service
metadata:
  name: studio-service
  labels:
    run: studio-service
spec:
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: actress
  type: LoadBalancer
