apiVersion: v1
kind: Service
metadata:
  name: user-reader
  labels:
    run: user-reader
spec:
  ports:
  - name: https
    protocol: TCP
    port: 7000
    targetPort: 443
  - name: http
    protocol: TCP
    port: 7001
    targetPort: 80
  selector:
    app: user-reader
  type: LoadBalancer
