apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: timetoteach-ui-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timetoteach-ui-server
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: timetoteach-ui-server
        tier: backend
        bump: bump-60
    spec:
      imagePullSecrets:
        - name: myregistrykey
      volumes:
        - name: "timetoteach-ui-server-tls"
          secret:
            secretName: "timetoteach-ui-server-tls"
        - name: "nginx-timetoteach-ui-server-dev-proxf-conf"
          configMap:
            name: "nginx-timetoteach-ui-server-dev-proxf-conf"
            items:
              - key: "nginx-timetoteach-ui-server.conf"
                path: "nginx-timetoteach-ui-server.conf"
      containers:
        - name: nginx
          image: nginx:1.7.9
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 443
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
          volumeMounts:
            - name: "nginx-timetoteach-ui-server-dev-proxf-conf"
              mountPath: "/etc/nginx/conf.d"
            - name: "timetoteach-ui-server-tls"
              mountPath: "/etc/tls"
        - name: timetoteach-ui-server
          image: eu.gcr.io/time-to-teach/timetoteach_ui_server:0.0.1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 512Mi
          ports:
            - containerPort: 9000
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 120
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 120
            timeoutSeconds: 5
