apiVersion: v1
kind: Service
metadata:
  name: es-and-os-reader-service
  labels:
    run: es-and-os-reader-service
spec:
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: es-and-os-reader
  type: LoadBalancer
