apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: studio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studio
  strategy:
    type: RollingUpdate
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: studio
        tier: backend
        bump: bump-10
    spec:
      imagePullSecrets:
        - name: myregistrykey
      volumes:
        - name: "studio-tls"
          secret:
            secretName: "studio-tls"
        - name: "nginx-studio-dev-proxf-conf"
          configMap:
            name: "nginx-studio-dev-proxf-conf"
            items:
              - key: "nginx-studio.conf"
                path: "nginx-studio.conf"
      containers:
        - name: nginx
          image: nginx:1.7.9
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 443
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
          volumeMounts:
            - name: "nginx-studio-dev-proxf-conf"
              mountPath: "/etc/nginx/conf.d"
            - name: "studio-tls"
              mountPath: "/etc/tls"
        - name: studio
          image: eu.gcr.io/api-event-horizon-151020/studio:0.0.2
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka.dev.sudostream.io:9092
          resources:
            limits:
              cpu: 100m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 512Mi
          ports:
            - containerPort: 9010
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 300
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 300
            timeoutSeconds: 5
