apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: genre-romcom-screenwriter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genre-romcom-screenwriter
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: genre-romcom-screenwriter
        tier: backend
        bump: bump-10
    spec:
      imagePullSecrets:
        - name: myregistrykey
      volumes:
        - name: "genre-romcom-screenwriter-tls"
          secret:
            secretName: "genre-romcom-screenwriter-tls"
        - name: "nginx-genre-romcom-screenwriter-dev-proxf-conf"
          configMap:
            name: "nginx-genre-romcom-screenwriter-dev-proxf-conf"
            items:
              - key: "nginx-genre-romcom-screenwriter.conf"
                path: "nginx-genre-romcom-screenwriter.conf"
      containers:
        - name: nginx
          image: nginx:1.7.9
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 700Mi
            requests:
              cpu: 100m
              memory: 500Mi
          ports:
            - containerPort: 443
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
          volumeMounts:
            - name: "nginx-genre-romcom-screenwriter-dev-proxf-conf"
              mountPath: "/etc/nginx/conf.d"
            - name: "genre-romcom-screenwriter-tls"
              mountPath: "/etc/tls"
        - name: genre-romcom-screenwriter
          image: eu.gcr.io/api-event-horizon-151020/genre-romcom-screenwriter:0.0.2
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka.dev.sudostream.io:9092
          resources:
            limits:
              cpu: 100m
              memory: 700Mi
            requests:
              cpu: 100m
              memory: 500Mi
          ports:
            - containerPort: 9020
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 20
            timeoutSeconds: 5
