apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: actress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: actress
  strategy:
    type: RollingUpdate
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: actress
        tier: backend
        bump: bump-178
    spec:
      imagePullSecrets:
        - name: myregistrykey
      volumes:
        - name: "scriptwriter-tls"
          secret:
            secretName: "scriptwriter-tls"
        - name: "nginx-actress-dev-proxf-conf"
          configMap:
            name: "nginx-actress-dev-proxf-conf"
            items:
              - key: "nginx-actress.conf"
                path: "nginx-actress.conf"
      containers:
        - name: nginx
          image: nginx:1.7.9
          imagePullPolicy: Always
          ports:
            - containerPort: 443
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
          volumeMounts:
            - name: "nginx-actress-dev-proxf-conf"
              mountPath: "/etc/nginx/conf.d"
            - name: "scriptwriter-tls"
              mountPath: "/etc/tls"
        - name: actress
          image:  eu.gcr.io/api-event-horizon-151020/actress:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka.dev.sudostream.io:9092
          resources:
            limits:
              cpu: 400m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          ports:
            - containerPort: 9000
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 20
            timeoutSeconds: 5
