apiVersion: v1
kind: Service
metadata:
  name: school-reader
  labels:
    run: school-reader
spec:
  ports:
    - name: https
      protocol: TCP
      port: 7006
      targetPort: 443
    - name: http
      protocol: TCP
      port: 7007
      targetPort: 80
  selector:
    app: school-reader
  type: LoadBalancer
