apiVersion: v1
kind: Service
metadata:
  name: school-reader
  labels:
    run: school-reader
spec:
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: user-reader
  type: LoadBalancer
