apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: timetoteach-ui-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: timetoteach-ui-server
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: timetoteach-ui-server
        tier: backend
        bump: bump-156
    spec:
      imagePullSecrets:
        - name: myregistrykey
      volumes:
        - name: "timetoteach-ui-server-tls"
          secret:
            secretName: "timetoteach-ui-server-tls"
        - name: "nginx-timetoteach-ui-server-dev-proxf-conf"
          configMap:
            name: "nginx-timetoteach-ui-server-dev-proxf-conf"
            items:
              - key: "nginx-timetoteach-ui-server.conf"
                path: "nginx-timetoteach-ui-server.conf"
      containers:
        - name: nginx
          image: nginx:1.7.9
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 768Mi
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 443
            - containerPort: 80
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
          volumeMounts:
            - name: "nginx-timetoteach-ui-server-dev-proxf-conf"
              mountPath: "/etc/nginx/conf.d"
            - name: "timetoteach-ui-server-tls"
              mountPath: "/etc/tls"
        - name: timetoteach-ui-server
          image: eu.gcr.io/time-to-teach-zone/www-time-to-teach:latest
          imagePullPolicy: Always
          env:
            - name: TIMETOTEACH_FACEBOOK_ID
              valueFrom:
                secretKeyRef:
                  name: timetoteachfacebookid
                  key: timetoteachfacebookid
                  optional: true
            - name: TIMETOTEACH_FACEBOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: timetoteachfacebooksecret
                  key: timetoteachfacebooksecret
                  optional: true
          resources:
            limits:
              cpu: 400m
              memory: 1536Mi
            requests:
              cpu: 200m
              memory: 1024Mi
          volumeMounts:
            - name: "timetoteach-ui-server-tls"
              mountPath: "/etc/tls"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 90
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 90
            timeoutSeconds: 5
