apiVersion: batch/v1
kind: Job
metadata:
  name: esandospopulator
spec:
  template:
    metadata:
      name: esandospopulator
    spec:
      containers:
      - name: esandospopulator
        image: eu.gcr.io/time-to-teach/esandospopulator:0.0.19
        imagePullPolicy: IfNotPresent
        env:
          - name: MONGODB_CONNECTION_URI
            value: mongodb://ttt:hello321@timetoteachdevmongodb-shard-00-00-sss8y.gcp.mongodb.net:27017,timetoteachdevmongodb-shard-00-01-sss8y.gcp.mongodb.net:27017,timetoteachdevmongodb-shard-00-02-sss8y.gcp.mongodb.net:27017/test?ssl=true&replicaSet=TimeToTeachDevMongoDB-shard-0&authSource=admin
          - name: MONGODB_HOST
            value: "10.0.2.2"
          - name: MONGODB_PORT
            value: "27017"
        resources:
          limits:
            cpu: 500m
            memory: 2048Mi
          requests:
            cpu: 200m
            memory: 1024Mi
      restartPolicy: Never
