apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-reader
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-reader
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: user-reader
        tier: backend
        bump: bump-16
    spec:
      imagePullSecrets:
        - name: myregistrykey
      volumes:
        - name: "user-reader-tls"
          secret:
            secretName: "user-reader-tls"
        - name: "nginx-user-reader-dev-proxf-conf"
          configMap:
            name: "nginx-user-reader-dev-proxf-conf"
            items:
              - key: "nginx-user-reader.conf"
                path: "ngin-user-reader.conf"
      containers:
        - name: nginx
          image: nginx:1.7.9
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 443
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
          volumeMounts:
            - name: "nginx-user-reader-dev-proxf-conf"
              mountPath: "/etc/nginx/conf.d"
            - name: "user-reader-tls"
              mountPath: "/etc/tls"
        - name: user-reader
          image: eu.gcr.io/time-to-teach/user-reader:0.0.1-10
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGODB_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: mongoconnectionuri
                  key: mongoconnectionuri
                  optional: true
            - name: LOCAL_MONGO_DB
              value: "false"
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: kafkasecrets
                  key: kafkabootstrapservers
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 9000
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 120
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 120
            timeoutSeconds: 5
