apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: school-reader
spec:
  replicas: 2
  selector:
    matchLabels:
      app: school-reader
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: school-reader
        tier: backend
        bump: bump-60
    spec:
      imagePullSecrets:
        - name: myregistrykey
      volumes:
        - name: "mongodb-cacerts"
          secret:
            secretName: "mongodbkeystore"
        - name: "school-reader-tls"
          secret:
            secretName: "school-reader-tls"
        - name: "nginx-school-reader-dev-proxf-conf"
          configMap:
            name: "nginx-school-reader-dev-proxf-conf"
            items:
              - key: "nginx-school-reader.conf"
                path: "nginx-school-reader.conf"
      containers:
        - name: nginx
          image: nginx:1.7.9
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 768Mi
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 443
            - containerPort: 80
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
          volumeMounts:
            - name: "nginx-school-reader-dev-proxf-conf"
              mountPath: "/etc/nginx/conf.d"
            - name: "school-reader-tls"
              mountPath: "/etc/tls"
        - name: school-reader
          image: eu.gcr.io/time-to-teach-zone/school-reader:latest
          imagePullPolicy: Always
          env:
            - name: MONGODB_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: mongoconnectionuri
                  key: mongoconnectionuri
                  optional: true
            - name: LOCAL_MONGO_DB
              value: "false"
            - name: MONGODB_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodbkeystorepassword
                  key: mongodbkeystorepassword
                  optional: true
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: kafkasecrets
                  key: kafkabootstrapservers
            - name: SYSTEM_EVENTS_TOPIC
              value: "h1t96dt8-SYSTEM_ALL_EVENTS_LOG"
            - name: KAFKA_SASL_JASS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafkasasljassusername
                  key: kafkasasljassusername
            - name: KAFKA_SASL_JASS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafkasasljasspassword
                  key: kafkasasljasspassword
          volumeMounts:
            - name: "mongodb-cacerts"
              mountPath: "/etc/ssl/"
          resources:
            limits:
              cpu: 200m
              memory: 768Mi
            requests:
              cpu: 100m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 60
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 60
            timeoutSeconds: 5
